# Change these first
owner: dothq # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Website
    url: https://dothq.co
  - name: API
    url: https://dothq.co/api
  - name: NTP
    url: https://ntp.dothq.co
  - name: Services
    url: https://services.dothq.co
  - name: dothq.link
    url: https://dothq.link
  - name: dothq.design
    url: https://dothq.design

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.dothq.co
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /uptime
  logoUrl: https://avatars.githubusercontent.com/u/50807955?v=4
  name: Dot HQ Status
  introTitle: "Status reports for all Dot HQ programs and services."
  introMessage: View and check the status of Dot HQ services and products in real-time with status reports when something goes wrong.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER
    - title: Twitter
      href: https://twitter.com/DotBrowser

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
